<!DOCTYPE html>
<html>
<head>
	<title><?=$this->escape($webinarInfo['name'])?></title>
	<link rel="stylesheet" type="text/css" href="/statics/css/common/common.css">
	<link rel="stylesheet" type="text/css" href="/statics/css/live.css">
	<script src="/statics/assets/wap/js/jquery.min.js"></script>
	<script type="text/javascript" src='http://g.alicdn.com/de/prismplayer/1.5.7/prism-flash-min.js'></script>
	<script type="text/javascript" src='/statics/assets/wap/js/jquery.face.js'></script>
	<script type="text/javascript" src='/statics/js/wwwpc/sea.js'></script>
	<script type="text/javascript" src='/statics/js/wwwpc/seajs-text.js'></script>
</head>
<body>
<div id="live">
	<div class="live-title">
		<div class="fl"><span class="fl"><?=$this->escape($info['name'])?></span><span class="fl subscribe-btn j-subscribe">已订阅</span></div>
		<div id="user-info">
		</div>
		<div class="fr name"><i class="j-user-header"><img src="/statics/img/mengzhuleader01.png" class="avatar" /></i><a class="js-nick">欢迎你，用户昵称</a></div>
		<div class="fr no-name"><img src="/statics/img/mengzhuleader01.png" class="avatar" />


		<a class="js-load" href="http://u.dev.zmengzhu.com/?jump=www" target="_blank">点击登陆</a></div>
		<div class="avatar-tip clear fr">
			<em class="triangle"></em>
			<div style="text-align: center; margin: 10px auto"> <i class="j-tab-login">切换</i> | <i class="j-logout">退出</i></div>
			<p class="js-uid">盟主号：</p>
			<p><a href="<?=$service['business']?>/" target="_blank">我的控制台</a></p>
		</div>
	</div>
	
	<div class="watch-live clear">
		<div class="fl player-content">
			<div id="J_prismPlayer" class="prism-player"></div>
			<div class="player-tip z-index-9"><?=$statusType;?></div>
			<!--视频提示-->
			 <div class="j-live-tip z-index-9" style="display: none">
			   <p>播放完成，请在直播回放中选择观看其它视频</p>
			 </div>
			 <!--付费视频-->
			 <div class="j-pay-video z-index-9" id="js-video-pwd" style="display: none">
				 <p>该视频需要密码观看，请输入密码后继续观看</p>
	             <input type="text" placeholder="请输入密码" class="j-check-psw wirte-psw"><span class="j-confirm-psw confirm-psw">确定</span>
			 </div>
			<div class="j-pay-video z-index-9" id="js-video-pay" style="display: none">
				<p>该视频仅频道会员和付费用户才有权限观看，付费价格为<?=$amount?>元，一个月有效</p>
				<span class="j-buy-video buy-video fl">立即购买</span>
				<?php if($memberCategory):?>
					<span class="j-open-member open-member fl">开通会员</span>
				<?php endif;?>
		    </div>
			<div class="j-pay-video z-index-9" id="js-vido-vip" style="display: none">
				<p>该视频仅频道会员用户才有权限观看</p>
				<?php if($memberCategory):?>
					<span class="j-open-member open-member open-vip">开通会员</span>
				<?php endif;?>
			</div>
			 <div class="mask"></div>

		</div>
		<div class="fr chat">
			<div class="scroll-content">
			</div>
			<div class="btn-area">
				<img src="/statics/img/expression.png" class="js-qqface" data-qqmotion-input="saytext"
				data-qqmotion-imgpath="/statics/img/arclist/"/>
				<img src="/statics/img/gift.png" class="js-gift" />
			</div>
			<input type="text" name="" placeholder="请输入内容" class="js-chatContent" id="saytext" name="saytext">
			<button class="js-send">发送</button>
			<div class="prohibit"><a href="">登录</a></div>
		</div>
		<div class="blank10"></div>
		<div class="clear describe">
			<div class="describe-title"><?=$this->escape($webinarInfo['name'])?>
			<span><?=date('Y-m-d H:i', $webinarInfo['start_time']);?> &nbsp;&nbsp;|&nbsp;&nbsp; <img class="j-share-channel" src="/statics/img/live-share.png"/> 
				<div class="share-content">
					<input type="text" name="" class="fl" id="link_text">
					<button class="fl js-copy" data-clipboard-target="#link_text" flag="1">复制</button>
				</div>
			</span></div>
			<div class="live-num"><img src="/statics/img/watch.png"/><?=$info['popular']?>人</div>
			<div class="describe-content"><?=$this->escape($webinarInfo['introduction'])?></div>
		</div>
	</div>
	<div class="nav-tab clear">
		<ul class="clear">
			<li class="select js-back">直播回放</li>
			<li class="js-introduce">频道介绍</li>
		</ul>
		<div class="playback-list clear">
			
		</div>
		<div class="channel-introduce">
			<div class="channel-title"><?=$this->escape($info['name'])?></div>
			<div class="channel-content"><?=$this->escape($info['introduction'])?></div>
		</div>
	</div>
</div>
<div class="push-box">
	<p>请在APP中对主播进行打赏</p>
	<button class="fl cancel">取消</button>
	<button class="fl download" >下载APP</button>
</div>
<!--登录-->
<!--  <iframe src="http://u.dev.mengzhu.tv/?jump=www" width="800" height="600" scrolling="no" frameborder="0" class="j-login"></iframe>
 --> 
 <!--购买视频-->
 <div class="j-buy-view">
   <img src="/statics/img/close_btn.png" class="fr j-close">
  <div class="fl pay-money-inner">
      <p class="total-money">￥<?=$amount?></p>
      <div class="pay-way-out clear">
		  <?php
		  if($payInfo) {
			  $balanceString = $payInfo['balanceString'];
			  $balance = $payInfo['balance'];
			  $coinString = $payInfo['coinString'];
			  $coin = $payInfo['coin'];
		  } else {
			  $balanceString = 0;
			  $balance = 0;
			  $coinString = 0;
			  $coin = 0;
		  }
		  ?>
         <ul class="j-select-pay">
			 <li class="cur-pay" data-money="<?=$coin?>" data-method="coin">银两支付</li>
			 <li data-money="<?=$balance?>" data-method="balance">余额支付</li>
			 <li data-method="weixin_qr">微信支付</li>
			 <li data-method="alipay_pc">支付宝支付</li>
		 </ul>
         <div class="pay-way-inner">
            <div class="cont-none cont-block center-algin fl" data="coin">
                <img src="/statics/img/coin_pay.png">
                <p id="coin">当前银两：<?=$coinString?>两</p>
                <span class="pay-btn j-coin-pay">确认支付</span>
            </div>
            <div class="cont-none center-algin fl">
                <img src="/statics/img/uu_pay.png">
                 <p id="balance">当前余额：<?=$balanceString?>两</p>
                <span class="pay-btn j-balance-pay">确认支付</span>
            </div>
            <div class="cont-none center-algin fl">
                <img src="/statics/img/uu_pay.png" id="wexin_qr_img">
                <p>请使用微信扫码支付</p>
            </div>
            <div class="cont-none center-algin fl">
                <img src="/statics/img/uu_pay.png">
                <p>请在弹出的新窗口中完成支付</p>
            </div>

         </div>
      </div>

  </div>
 </div>

  <!--购买会员-->
<?php if($memberCategory):?>
<div class="pay-money-content j-vip">
   	<img src="/statics/img/close_btn.png" class="fr j-close">
  	<div class="fl member-type j-member-type">
		  <?php
		  	$memberMap = [
		  		'1' => '1个月会员',
				'2' => '3个月会员',
				'3' => '6个月会员',
				'4' => '12个月会员',
			];
		  ?>
		  <?php foreach ($memberCategory as $key => $member):?>
			  <span class="<?=($key == 0) ? 'cur-type': " "?>" data-money="<?=$member['amount']?>" data-mid="<?=$member['id']?>"><?=$memberMap[$member['type']]?></span>
		  <?php endforeach;?>
  	</div>
  	<div class="fl pay-money-inner">
		<p class="total-money j-vip-money">￥<?=$memberCategory[0]['amount']?></p>
		<div class="pay-way-out clear">
		  <?php
		  if($payInfo) {
			  $balanceString = $payInfo['balanceString'];
			  $balance = $payInfo['balance'];
			  $coinString = $payInfo['coinString'];
			  $coin = $payInfo['coin'];
		  } else {
			  $balanceString = 0;
			  $balance = 0;
			  $coinString = 0;
			  $coin = 0;
		  }
		  ?>
			<ul class="j-vip-pay">
				<li class="cur-pay" data-money="<?=$coin?>" data-method="coin">银两支付</li>
				<li data-money="<?=$balance?>" data-method="balance">余额支付</li>
				<li data-method="weixin_qr">微信支付</li>
				<li data-method="alipay_pc">支付宝支付</li>
			</ul>
         	<div class="pay-way-inner j-vip-inner">
            	<div class="cont-none cont-block center-algin fl" data="coin">
                	<img src="/statics/img/coin_pay.png">
                	<p id="coin">当前银两：<?=$coinString?>两</p>
                	<span class="pay-btn j-vip-coin-pay">确认支付</span>
				</div>
            	<div class="cont-none center-algin fl">
                	<img src="/statics/img/uu_pay.png">
                 	<p id="balance">当前余额：<?=$balanceString?>两</p>
                	<span class="pay-btn j-vip-balance-pay">确认支付</span>
            	</div>
            	<div class="cont-none center-algin fl">
					<img src="/statics/img/uu_pay.png" id="wexin_qr_img_vip">
                	<p>请使用微信扫码支付</p>
            	</div>
            	<div class="cont-none center-algin fl">
                	<img src="/statics/img/uu_pay.png">
                	<p>请在弹出的新窗口中完成支付</p>
            	</div>
         	</div>
      	</div>
  	</div>
</div>
<?php endif;?>
 <!--alert-->
 <div class="alert-pop">
    <p class="alert-tip"></p>
    <span class="pop-confirm">确定</span>
 </div>
 <div class="mask-global">
 </div>
</body>
<script>
	var  liveStatus = "<?=$info['status']?>" == 1 ? true : false;

	// 初始化播放器
    var player = new prismplayer({
        id: "J_prismPlayer",  // 容器id
        source: "<?=$info['stream_url']?>",// 视频地址
        autoplay: true,       //自动播放：是
        width: "840px",       // 播放器宽度
        height: "476px",      // 播放器高度
        cover:"<?=$this->escape($info['share_info']['share_image'])?: '/statics/assets/wap/img/webinar.jpg'?>", //播放器默认封面图片
        isLive: liveStatus,        //播放器是否为直播状态，直播时禁止拖动进度条
        showBuffer:true,      //播放时缓冲图标
        autoplay: true,      //自动播放
    });

	// 播放完成
	player.on('ended', function(){
		if (!liveStatus) {
			$(".j-live-tip").empty().html('<p>播放完成，请在直播回放中选择观看其它视频</p>').show();
		}
	});
	player.on('play', function(){
		$(".j-live-tip").hide();
	});

    // login user
	var userInfo = <?=json_encode($userInfo);?>;
	var qrCodeInfo = <?=json_encode($info['share_info']);?>;
	var logoutUrl = "<?=rtrim($business, '/') . '/user/exit';?>";
	// 是否订阅
	var isSubscribe = <?=$isSubscribe;?>;
	// 订阅地址 参数 cid：频道id act:动作 (sub订阅，can取消订阅) GET请求方式
	var subscribeUrl = '/wap/user/subscribe';
	// 验证密码 参数 cid：频道id wid:webinarId  pwd:密码 POST请求方式
	var checkPwd = '/wap/info/checkPwd';
	// 回放列表 参数 channel_id：频道id offset,limit GET请求方式
	var channelRecordList = '/home/live/recordList';

	var isFree = "<?=$isFree?>";
	var freeTime = "<?=$freeTime?>";
	var liveType = "<?=$liveType?>";
	var isVip = "<?=$isVip?>";
	var amount = "<?=$amount?>";
	var videoStatus = "<?=$videoStatus?>";
	var webinarId = "<?=$webinarInfo['id']?>";
	var channelId = "<?=$channelId?>";
	var adminId = "<?=$info['uid']?>";
	var channelNotice = "<?=$this->escape($info['notice'])?>";

	seajs.config({
	  paths:{
	    'base':"/statics/js/wwwpc/"
	  },
	  alias: {
	    "index":"base/index",
	  }
	});
    seajs.use("index");

	var pageinfo = {
		<?php foreach ($pageInfo as $k => $v) : ?>
		'<?=$k?>':'<?=$this->escape($v)?>',
		<?php endforeach; ?>
		'isMobile':'1',
		'is_gag':'0',
		'log_service':'http://log.vhall.com:9101/gelf',
		'matchTheLink':'0',
		'kickOut':'0',
		'curr_presenter':'0',
		'appName':'smb',
		'hide_powered' :  0 ,
		'user_avatar':  '',
		'ppt_msg':'<?=isset($info['ppt_msg']) ? $info['ppt_msg'] : ''?>',
		'date': '<?=date('Y-m-d')?>'
	};
	var isPublic = "<?=$info['is_public']?>";
	var myUid = typeof(userInfo.uid) == 'undefined' ? 0 : userInfo.uid;
	<?php if ($memberCategory):?>
	var memberId = "<?=$memberCategory[0]['id'];?>";
	var vipAmount = "<?=$memberCategory[0]['amount'];?>";
	<?php else:?>
	var memberId = 0;
	var vipAmount = 0;
	<?php endif;?>
	var weixinSelected = false;
	var payMethod = false;
	var money = "<?=isset($payInfo['coin']) ? $payInfo['coin'] : 0?>";
	
</script>
<script src="/statics/assets/wap/js/pushstream.js?v=20170525" type="text/javascript"></script>
<script type="text/javascript" src="/statics/js/pc_pushstream.js?v=20170622"></script>
<script type="text/javascript" src="/statics/assets/wap/js/socket.io.js"></script>
<script type="text/javascript" src="/statics/assets/wap/js/vhall_socket.js"></script>
<script src="/statics/js/wwwpc/clipboard.min.js"></script>
<script>
	// 聊天监听
	var msg_listen = pageinfo.msg_listen_srv.split(':');
	pushstream.useSSL = (msg_listen[0] == 'https');
	pushstream.host = msg_listen[1].substring(2);
	pushstream.port = msg_listen[2] ? msg_listen[2] : '';
	pushstream.addChannel('smb.' + pageinfo.room);
	pushstream.addChannel('smb.u' + myUid);
	pushstream.connect();

	<?php if($isFree == 0 && $freeTime > 0):?>
	setTimeout(function(){
		window.location.reload();
	}, freeTime*1000);
	<?php endif;?>
	<?php if(!$info['stream_url']):?>
	if(videoStatus == 1) {
		$(".j-live-tip").empty().html('<p>直播即将开始，请耐心等待</p>').show();
	} else if(videoStatus == 2 || videoStatus == 4) {
		$(".j-live-tip").empty().html('<p>播放完成，请在直播回放中选择观看其它视频</p>').show();
	} else {
		if (liveType == 2) {
			$("#js-vido-vip").show();
		} else if(liveType == 3) {
			$("#js-video-pay").show();
		} else {
			$("#js-video-pwd").show();
		}
	}
	<?php endif;?>
	var faceUrl="/statics/img/arclist/";
	$(".js-qqface").qqFace({
	    id : 'facebox',
	    assign:'saytext',
	    path:faceUrl //表情存放的路径
    });
    $(".js-qqface").click(function(){
    	var top = $(this).offset().top - $(".qqFace").height() - 133;
    	$(".qqFace").css({top:top,left:-1,});
    });

	var payVideo = false;
	// 购买付费视频h
	$(".j-select-pay").children('li').click(function(){
		payMethod = $(this).attr('data-method');

		if (payMethod == 'coin' || payMethod == 'balance') {
			// 判断余额银两
			money = $(this).attr('data-money');
		} else {
			if (payMethod == 'alipay_pc') {

			} else if(payMethod == 'weixin_qr' && weixinSelected == false) {

				weixinSelected = true;
			} else {
				return false;
			}
			if(payVideo) {
				return false;
			}
			payVideo = true;

			$.ajax({
				url: '/wap/info/buy',
				type: 'post',
				data: {'cid':channelId, 'wid':webinarId, 'pay_method':payMethod},
				success: function(res) {
					if (res.code == 200) {
						if (res.data.pay_method == 'weixin_qr') {
							$("#wexin_qr_img").attr('src', res.data.pay_agent);
						} else{
							window.open(res.data.pay_agent);
						}
					} else {
						alert(res.msg);
					}

					payVideo = false;
				},
				error: function(res) {
					alert("稍后重试");
					payVideo = false;
				}
			});
		}
	});

	$(".j-coin-pay,.j-balance-pay").click(function(){
		if (payVideo) {
			return false;
		}
		payVideo = true;
		if (money < amount) {
			msg = (payMethod == 'coin') ? '银两不足' : '余额不足';
			alert(msg);
			return false;
		}

		$.ajax({
			url: '/wap/info/buy',
			type: 'post',
			data: {'cid':channelId, 'wid':webinarId, 'pay_method':payMethod},
			success: function(res) {
				if (res.code == 200) {
					if(res.data.is_paid == 1) {
						alert("支付成功");
						window.location.reload();
					} else {
						alert(res.msg);
					}
				} else {
					alert(res.msg);
				}
				payVideo = false;
			},
			error: function(res) {
				alert("稍后重试");
				payVideo = false;
			}
		});
	});

	var payVip = false;
	$(".j-vip-pay").children('li').click(function(){
		payMethod = $(this).attr('data-method');
		if(payMethod == 'coin' || payMethod == 'balance') {
			// 判断余额银两
			money = $(this).attr('data-money');
		} else {
			if (payMethod == 'alipay_pc') {

			} else if(payMethod == 'weixin_qr') {

			} else {
				return false;
			}

			if(payVip) {
				return false;
			}
			payVip = true;

			$.ajax({
				url: '/wap/vip/pay',
				type: 'get',
				data: {'cid':channelId, 'mid':memberId, 'pay_method':payMethod},
				success: function(res) {
					if (res.code == 200) {
						if (res.data.pay_method == 'weixin_qr') {
							$("#wexin_qr_img_vip").attr('src', res.data.pay_agent);
						} else{
							window.open(res.data.pay_agent);
						}
					} else {
						alert(res.msg);
					}
					payVip = false;
				},
				error: function(res) {
					alert("稍后重试");
					payVip = false;
				}
			});
		}
	});

	$(".j-vip-coin-pay,.j-vip-balance-pay").click(function(){
		if(payVip) {
			return false;
		}
		payVip = true;

		if (money < vipAmount) {
			msg = (payMethod == 'coin') ? '银两不足' : '余额不足';
			alert(msg);
			return false;
		}

		$.ajax({
			url: '/wap/vip/pay',
			type: 'get',
			data: {'cid':channelId, 'mid':memberId, 'pay_method':payMethod},
			success: function(res) {
				if (res.code == 200) {
					if(res.data.is_paid == 1) {
						alert("支付成功");
						window.location.reload();
					} else {
						alert(res.msg);
					}
				} else {
					alert(res.msg);
				}
				payVip = false;
			},
			error: function(res) {
				alert("稍后重试");
				payVip = false;
			}
		});
	});
</script>
</html>